### ISSUE TITLE
I need a callback function for node quality, or directly include it in the JSON of the API response.

### ISSUE THREAD

**Issue by kaol2046** [fiatrete/DAN-Stable-Diffusion-Computing-Network#34]
How can I know the quality of the node I'm using when request API? callback function for node quality, or directly include it in the JSON of the API response.

**Comment by fiatrete** [comment]
What do you mean by "node quality"? What specific problem are you encountering?

**Comment by DiligentCatCat** [comment]
> Some requests slow and some requests fail.

I have just developed asynchronous version of txt2img and img2img, which will return a task ID immediately. New APIs are also provided to query the state of a certain task.

Well, you may have to wait for @fiatrete to deploy them. After that, you can have a try! ;-)

**Comment by fiatrete** [comment]
> > Some requests slow and some requests fail.
> 
> I have just developed asynchronous version of txt2img and img2img, which will return a task ID immediately. New APIs are also provided to query the state of a certain task.
> 
> Well, you may have to wait for @fiatrete to deploy them. After that, you can have a try! ;-)

Don't forget the documents!

**Comment by DiligentCatCat** [comment]
> > > Some requests slow and some requests fail.
> > 
> > 
> > I have just developed asynchronous version of txt2img and img2img, which will return a task ID immediately. New APIs are also provided to query the state of a certain task.
> > Well, you may have to wait for @fiatrete to deploy them. After that, you can have a try! ;-)
> 
> Don't forget the documents!

Sorry for that, the docs are ready in another PR
