### ISSUE TITLE
a pagination bug in the donors section

### ISSUE THREAD

**Issue by dxxxp** [fiatrete/DAN-Stable-Diffusion-Computing-Network#35]
Great project!  
However, I have noticed an issue you've encountered while using the "Donors" list: The pagination function may have some bugs.   Currently, there are only three donors, but the pagination indicator in the bottom right corner shows that there are two pages.   
When switching to the second page, no data is displayed.   
I am looking forward to the issue being fixed as soon as possible.

**Comment by usydapeng** [comment]
I had the same issue as well. Additionally, it seems like the [list of donor](https://www.opendan.ai/nodes) is not sorted, but the [roadmap](https://github.com/fiatrete/DAN-Stable-Diffusion-Computing-Network#roadmap) states that it should be sorted based on each donor's workload.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/5045493/231063861-782910ee-575d-4763-8468-0e8694350225.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/5045493/231063726-385786c2-3fa6-4fc5-bb7e-f8eea4035498.png">

**Comment by usydapeng** [comment]
@dxxxp @fiatrete  This issue seems relatively simple, so I fixed the pagination and sorting bugs on the fly. #45
