### ISSUE TITLE
Error occurred when running dan_run.py in the example folder with error code 1000

### ISSUE THREAD

**Issue by yh1225** [fiatrete/DAN-Stable-Diffusion-Computing-Network#56]
![image](https://user-images.githubusercontent.com/7540966/232394814-d3fe8bf6-e2fb-489e-9328-899e0b7ea5fd.png)

**Comment by yh1225** [comment]
Nothing code has changed, just ran the example file in example, what is the reason

**Comment by fiatrete** [comment]
I just refactored the code for example, please try again.

**Comment by yh1225** [comment]
Done
